### ISSUE TITLE
Deploy on mvnrepository.com

### ISSUE THREAD

**Issue by ddolzan** [languagetoys/spacy4j#16]
Could you deploy this library on [mvnrepository.com](https://mvnrepository.com/)? 
It would be useful for include it in other projects without have to download and compile the source code..

**Comment by manzurola** [comment]
Hey @ddolzan, I've been wanting to do this for a while now, didn't get to it. Perhaps will have some time this week..

But for now, did you try to download it via Github Packages, where it's currently deployed?
You can follow [these instructions](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages) on how to setup it up as a maven repository and install this package.

Let me know if you need help here.

**Comment by ddolzan** [comment]
Awesome! Anyway a deploy on mvnrepository would be perfect to use it without editing the maven settings or the pom.xml of the project. Thank you for your quick response!

**Comment by manzurola** [comment]
Heya @ddolzan, deployment to maven repository was done a few minutes ago.
Can you please confirm you have proper access without additional configuration?
It might take a while till you can find it at [https://search.maven.org/](https://search.maven.org/), but already available at [https://repo1.maven.org/maven2/io/github/manzurola/](https://repo1.maven.org/maven2/io/github/manzurola/).

**Comment by manzurola** [comment]
Done. Thanks for the feedback @ddolzan
